### ISSUE TITLE
Unable to start server: Function not implemented

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/cyclonedx-bom-repo-server#68]
I'm unable to start the bom-repo-server. I'm testing on an Apple M1 Pro, which can run x86_64 containers under emulation. It works, but its slow. Not sure if platform is related to this error or not though. Here's the stack trace when starting the Docker container:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at CycloneDX.BomRepoServer.Program.Main(String[] args) in /home/runner/work/cyclonedx-bom-repo-server/cyclonedx-bom-repo-server/CycloneDX.BomRepoServer/Program.cs:line 33
qemu: uncaught target signal 6 (Aborted) - core dumped
```

I have attempted to start the container with and without the environment variables, with the same result.
* REPO__DIRECTORY
* ALLOWEDMETHODS__GET
* ALLOWEDMETHODS__POST
* ALLOWEDMETHODS__DELETE

**Comment by magnusp** [comment]
See https://github.com/dotnet/aspnetcore/issues/38876#issuecomment-994037119 for possible current situation and a temporary fix that could apply here

**Comment by coderpatros** [comment]
This shouldn't be an issue now with #67 done
